# Generated by Django 6.0.6 on 2026-06-07 16:05

import classifier.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=classifier.models.dataset_upload_path)),
                ('target_column', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_preloaded', models.BooleanField(default=False)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(blank=True, null=True, upload_to=classifier.models.model_upload_path)),
                ('features', models.JSONField()),
                ('target', models.CharField(max_length=100)),
                ('coefficients', models.JSONField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('feature_importance', models.JSONField(blank=True, null=True)),
                ('test_size', models.FloatField(default=0.2)),
                ('params', models.JSONField(blank=True, null=True)),
                ('classes', models.JSONField(blank=True, null=True)),
                ('is_binary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
