# Generated by Django 6.0.6 on 2026-06-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='model_type',
            field=models.CharField(default='logistic', max_length=10),
        ),
    ]
